import type { HeritagePoint } from "../lib/types";

export const RED_FORT_POINTS: HeritagePoint[] = [
  { id:'red-fort/lahori-gate',     siteId:'red-fort', name:'Lahori Gate',
    tags:['history','military','architecture'], importance:3,
    centroid:[77.2385,28.6562], narrationSec:{history:95,architecture:80,kids:55} },
  { id:'red-fort/chatta-chowk',    siteId:'red-fort', name:'Chatta Chowk',
    tags:['culture_traditions','history'], importance:2,
    centroid:[77.2392,28.6560], narrationSec:{history:80,architecture:65,kids:50} },
  { id:'red-fort/naubat-khana',    siteId:'red-fort', name:'Naubat Khana',
    tags:['culture_traditions','architecture'], importance:2,
    centroid:[77.2399,28.6558], narrationSec:{history:75,architecture:85,kids:45} },
  { id:'red-fort/diwan-i-aam',     siteId:'red-fort', name:'Diwan-i-Aam',
    tags:['history','architecture'], importance:3,
    centroid:[77.2408,28.6557], narrationSec:{history:110,architecture:95,kids:60} },
  { id:'red-fort/rang-mahal',      siteId:'red-fort', name:'Rang Mahal',
    tags:['architecture','culture_traditions'], importance:2,
    centroid:[77.2415,28.6552], narrationSec:{history:85,architecture:100,kids:50} },
  { id:'red-fort/khas-mahal',      siteId:'red-fort', name:'Khas Mahal',
    tags:['history','architecture'], importance:2,
    centroid:[77.2417,28.6555], narrationSec:{history:80,architecture:90,kids:45} },
  { id:'red-fort/diwan-i-khas',    siteId:'red-fort', name:'Diwan-i-Khas',
    tags:['history','architecture'], importance:3,
    centroid:[77.2419,28.6558], narrationSec:{history:120,architecture:105,kids:65} },
  { id:'red-fort/hammam',          siteId:'red-fort', name:'Hammam',
    tags:['architecture'], importance:1,
    centroid:[77.2421,28.6561], narrationSec:{history:60,architecture:80,kids:40} },
  { id:'red-fort/moti-masjid',     siteId:'red-fort', name:'Moti Masjid',
    tags:['religion','architecture','history'], importance:2,
    centroid:[77.2418,28.6563], narrationSec:{history:90,architecture:85,kids:50} },
  { id:'red-fort/hayat-bakhsh-bagh',siteId:'red-fort',name:'Hayat Bakhsh Bagh',
    tags:['culture_traditions','architecture'], importance:2,
    centroid:[77.2414,28.6570], narrationSec:{history:75,architecture:80,kids:55} },
  { id:'red-fort/mumtaz-mahal',    siteId:'red-fort', name:'Mumtaz Mahal',
    tags:['history','culture_traditions'], importance:1,
    centroid:[77.2413,28.6548], narrationSec:{history:70,architecture:60,kids:40} },
];

export const RED_FORT_ENTRANCE: [number, number] = [77.2381, 28.6562]; // outside Lahori Gate
