// generated by scripts/pull-baseline.ts alongside content/baseline.geojson
export const BASELINE_META = {
  featureCount: 585,
  pulledAt: "2026-08-20",
  source: "OpenStreetMap contributors, via the Overpass API. ODbL.",
};
