import fs from "fs";
import path from "path";

const VOLUME_TEXT_URL =
  "https://archive.org/download/in.ernet.dli.2015.70478/2015.70478.List-Of-Muhammadan-And-Hindu-Monuments-Vol1_djvu.txt";
const VOLUME_XML_URL =
  "https://archive.org/download/in.ernet.dli.2015.70478/2015.70478.List-Of-Muhammadan-And-Hindu-Monuments-Vol1_djvu.xml";
const IMAGE_BASE = "https://archive.org/download/in.ernet.dli.2015.70478/page/n";

const root = path.resolve(__dirname, "..");
const vol1Path = path.join(root, "vol1.txt");
const vol1XmlPath = path.join(root, "vol1_djvu.xml");
const publicPagesDir = path.join(root, "public", "pages");
const contentDir = path.join(root, "content");

const SPATIAL_RE =
  /\b(north|south|east|west|yards|miles|kos|gaz|paces|adjoining|opposite|near|situated)\b/gi;

function sleep(ms: number) {
  return new Promise((r) => setTimeout(r, ms));
}

async function fetchOnce(url: string, outPath: string, label: string) {
  if (fs.existsSync(outPath)) {
    console.log(`${label} already present`);
    return;
  }
  console.log(`Downloading ${label}...`);
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${label} failed: ${res.status}`);
  const buf = Buffer.from(await res.arrayBuffer());
  fs.writeFileSync(outPath, buf);
  console.log(`${label}: ${buf.length} bytes`);
}

function pageTextsFromXml(xml: string): string[] {
  const pages: string[] = [];
  const re = /<OBJECT[^>]*data="[^"]+"[^>]*>([\s\S]*?)<\/OBJECT>/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(xml))) {
    const block = m[1];
    const lines: string[] = [];
    const lineRe = /<LINE>([\s\S]*?)<\/LINE>/g;
    let lm: RegExpExecArray | null;
    while ((lm = lineRe.exec(block))) {
      const wordRe = /<WORD[^>]*>([\s\S]*?)<\/WORD>/g;
      const words: string[] = [];
      let wm: RegExpExecArray | null;
      while ((wm = wordRe.exec(lm[1]))) {
        words.push(wm[1].trim());
      }
      if (words.length) lines.push(words.join(" "));
    }
    pages.push(lines.join("\n"));
  }
  return pages;
}

function pageTextsFromPlainText(text: string): string[] {
  const rawPages = text.split("\f").map((p) => p.trim());
  return rawPages.filter((p) => p.length > 100);
}

async function downloadImage(pageNo: number) {
  const url = `${IMAGE_BASE}n${pageNo}_w800.jpg`;
  const out = path.join(publicPagesDir, `n${pageNo}.jpg`);
  if (fs.existsSync(out)) return;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`image ${pageNo} failed: ${res.status}`);
  const buf = Buffer.from(await res.arrayBuffer());
  fs.writeFileSync(out, buf);
  console.log(`n${pageNo}.jpg (${buf.length} bytes)`);
}

async function main() {
  fs.mkdirSync(publicPagesDir, { recursive: true });
  fs.mkdirSync(contentDir, { recursive: true });

  await fetchOnce(VOLUME_TEXT_URL, vol1Path, "vol1.txt");
  await fetchOnce(VOLUME_XML_URL, vol1XmlPath, "vol1_djvu.xml");

  const xml = fs.readFileSync(vol1XmlPath, "utf8");
  const xmlPages = pageTextsFromXml(xml);
  console.log(`XML parse produced ${xmlPages.length} pages`);

  let pages: string[] = xmlPages;
  let splitMethod = "djvu.xml per-page objects";
  if (xmlPages.length < 10) {
    const text = fs.readFileSync(vol1Path, "utf8");
    const plain = pageTextsFromPlainText(text);
    console.log(`XML parse unreliable (${xmlPages.length}); falling back to plain text split (${plain.length})`);
    pages = plain;
    splitMethod = "plain text fallback";
  }
  console.log(`Split method: ${splitMethod}`);

  const scored = pages
    .map((p, i) => {
      const score = (p.match(SPATIAL_RE) || []).length;
      return { index: i, pageNo: i, text: p, score };
    })
    .sort((a, b) => b.score - a.score)
    .slice(0, 20)
    .sort((a, b) => a.pageNo - b.pageNo);

  console.log("Selected pages:", scored.map((s) => `n${s.pageNo} (score ${s.score})`).join(", "));

  for (const page of scored) {
    await downloadImage(page.pageNo);
    await sleep(500);
  }

  const outPath = path.join(contentDir, "pages.ts");
  const entries = scored
    .map(
      (p) =>
        `  { pageNo: ${p.pageNo}, text: ${JSON.stringify(p.text)}, imageUrl: "/pages/n${p.pageNo}.jpg" },`
    )
    .join("\n");

  const content = `// Generated by scripts/ingest.ts. Do not edit by hand.
// 20 pages chosen by density of spatial language from Vol 1 of the ASI
// "List of Muhammadan and Hindu Monuments, Delhi Province" (1916).
// Split method: ${splitMethod}.
export interface IngestedPage {
  pageNo: number;
  text: string;
  imageUrl: string;
}

export const PAGES: IngestedPage[] = [
${entries}
];
`;

  fs.writeFileSync(outPath, content, "utf8");
  console.log(`Wrote ${contentDir}/pages.ts`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});