import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "gemini-3.5-flash",
  "pageNo": 295,
  "mentions": [
    {
      "id": "m_295_1",
      "name": "The Flagstaff Tower, locally known as ‘ Baota.’",
      "type": "tower",
      "period": "Erected by the British.",
      "passage": "Some 400 yards to the north of Chauburji Mosque.",
      "passageOffset": [
        100,
        148
      ],
      "spatialClue": {
        "anchorName": "Chauburji Mosque",
        "bearing": "N",
        "distanceValue": 400,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_295_2",
      "name": "Chauburji.",
      "type": "mosque",
      "period": "Firoz Shah’s reign.",
      "passage": "At a little distance to the north of Pirghaib (No. 401).",
      "passageOffset": [
        1204,
        1260
      ],
      "spatialClue": {
        "anchorName": "Pirghaib",
        "bearing": "N",
        "distanceValue": null,
        "distanceUnit": null
      }
    }
  ],
  "candidates": [
    {
      "id": "c_295_1",
      "mentionId": "m_295_1",
      "centroid": [
        77.215236,
        28.68485035416236
      ],
      "uncertaintyRadiusM": 251.36675257358323,
      "status": "candidate",
      "matchedBaselineFeature": {
        "id": "w1487074888",
        "name": "unnamed building (w1487074888)",
        "distanceM": 141.99498518315028
      },
      "confidence": {
        "total": 0.7345296763132032,
        "parts": {
          "clueSpecificity": 0.95,
          "anchorPrecision": 0.6896551724137931,
          "sourceReliability": 0.9,
          "modernEvidence": 0.7175541639271015,
          "crossSourceAgreement": 0
        }
      },
      "evidence": {
        "anchorId": "chauburji-mosque",
        "anchorName": "Chauburji Mosque",
        "anchorSource": "osm:w1487074892",
        "anchorCentroid": [
          77.215236,
          28.681561
        ],
        "bearingDeg": 0,
        "distanceM": 365.76,
        "radiusParts": {
          "anchorPrecisionM": 45,
          "bearingSpreadM": 151.50275257358322,
          "distanceVaguenessM": 54.864,
          "floorTopUpM": 0
        },
        "baselineVerdict": "matched_existing",
        "baselineChecked": [
          {
            "id": "w1487074888",
            "name": "unnamed building (w1487074888)",
            "distanceM": 141.99498518315028,
            "insideRadius": true
          },
          {
            "id": "n12696121640",
            "name": "Allnutt's Celtic Cross",
            "distanceM": 359.62503522785255,
            "insideRadius": false
          },
          {
            "id": "n12806176744",
            "name": "Foundation Stone",
            "distanceM": 362.81879042391824,
            "insideRadius": false
          },
          {
            "id": "w1487074892",
            "name": "Chauburji Mosque",
            "distanceM": 365.7822410975202,
            "insideRadius": false
          },
          {
            "id": "w1410331570",
            "name": "Flagstaff Tower",
            "distanceM": 448.7941435875939,
            "insideRadius": false
          }
        ]
      }
    },
    {
      "id": "c_295_2",
      "mentionId": "m_295_2",
      "centroid": [
        77.213211,
        28.676295
      ],
      "uncertaintyRadiusM": 190,
      "status": "candidate",
      "matchedBaselineFeature": null,
      "confidence": {
        "total": 0.49178571428571427,
        "parts": {
          "clueSpecificity": 0.3,
          "anchorPrecision": 0.7142857142857143,
          "sourceReliability": 0.9,
          "modernEvidence": 0.35,
          "crossSourceAgreement": 0
        }
      },
      "evidence": {
        "anchorId": "pir-ghaib",
        "anchorName": "Pir Ghaib",
        "anchorSource": "osm:n2940614717",
        "anchorCentroid": [
          77.213211,
          28.676295
        ],
        "bearingDeg": 0,
        "distanceM": null,
        "radiusParts": {
          "anchorPrecisionM": 40,
          "bearingSpreadM": 0,
          "distanceVaguenessM": 150,
          "floorTopUpM": 0
        },
        "baselineVerdict": "representation_gap",
        "baselineChecked": [
          {
            "id": "n2940614717",
            "name": "Pir Ghaib",
            "distanceM": 0.05002956454993427,
            "insideRadius": false
          },
          {
            "id": "n2940449158",
            "name": "Ashoka Pillar",
            "distanceM": 301.93215100570563,
            "insideRadius": false
          },
          {
            "id": "n2940449157",
            "name": "Ajitgarh",
            "distanceM": 598.3286299822372,
            "insideRadius": false
          },
          {
            "id": "w1487074892",
            "name": "Chauburji Mosque",
            "distanceM": 617.9449271685445,
            "insideRadius": false
          },
          {
            "id": "w1426174592",
            "name": "Dharamshala",
            "distanceM": 872.2772802046871,
            "insideRadius": false
          }
        ]
      }
    }
  ]
};

export default page;
