import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "openai/gpt-oss-120b",
  "pageNo": 264,
  "mentions": [
    {
      "id": "m_264_1",
      "name": "Kunwari Begam ka Burj",
      "type": "tomb",
      "period": "Mughal",
      "passage": "Some 50 yards to the north of Qadam Sharif shrine, within the enclosure No. 348.",
      "passageOffset": [
        298,
        378
      ],
      "spatialClue": {
        "anchorName": "Qadam Sharif shrine",
        "bearing": "N",
        "distanceValue": 50,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_264_2",
      "name": "Baoli",
      "type": "stepwell",
      "period": "Timeof Fiioz Shah",
      "passage": "Some 20 yards from No. 351 towards east, wuthin the enclosure No. 348.",
      "passageOffset": [
        1125,
        1195
      ],
      "spatialClue": {
        "anchorName": "No. 351",
        "bearing": "E",
        "distanceValue": 20,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_264_3",
      "name": "Kali Masjid",
      "type": "mosque",
      "period": null,
      "passage": "About a furlough to the north of Qadam Sharif enclosure (No. 348).",
      "passageOffset": [
        1866,
        1932
      ],
      "spatialClue": {
        "anchorName": "Qadam Sharif",
        "bearing": "N",
        "distanceValue": 1,
        "distanceUnit": "furlongs"
      }
    }
  ],
  "candidates": [
    {
      "id": "c_264_1",
      "mentionId": "m_264_1",
      "centroid": [
        77.21538500000001,
        28.646562169270293
      ],
      "uncertaintyRadiusM": 145.7958440716979,
      "status": "candidate",
      "matchedBaselineFeature": {
        "id": "n2714555470",
        "name": "Kunwari Begum ka Burj",
        "distanceM": 15.196731852775825
      },
      "confidence": {
        "total": 0.6985461646365432,
        "parts": {
          "clueSpecificity": 0.95,
          "anchorPrecision": 0.45454545454545453,
          "sourceReliability": 0.9,
          "modernEvidence": 0.9478835218193786,
          "crossSourceAgreement": 0
        }
      },
      "evidence": {
        "anchorId": "qadam-sharif",
        "anchorName": "Qadam Sharif",
        "anchorSource": "osm:n2714497374",
        "anchorCentroid": [
          77.215385,
          28.646151
        ],
        "bearingDeg": 0,
        "distanceM": 45.72,
        "radiusParts": {
          "anchorPrecisionM": 120,
          "bearingSpreadM": 18.937844071697903,
          "distanceVaguenessM": 6.858,
          "floorTopUpM": 0
        },
        "baselineVerdict": "matched_existing",
        "baselineChecked": [
          {
            "id": "n2714555470",
            "name": "Kunwari Begum ka Burj",
            "distanceM": 15.196731852775825,
            "insideRadius": true
          },
          {
            "id": "n2714497374",
            "name": "Qadam Sharief s Tomb",
            "distanceM": 45.76448739568557,
            "insideRadius": false
          },
          {
            "id": "n2981346624",
            "name": "Graveyard",
            "distanceM": 139.26099374346578,
            "insideRadius": true
          },
          {
            "id": "n5389381021",
            "name": "Snooker tashi",
            "distanceM": 314.75586270017993,
            "insideRadius": false
          },
          {
            "id": "n6512337586",
            "name": "unnamed attraction (n6512337586)",
            "distanceM": 481.8999098390548,
            "insideRadius": false
          }
        ]
      }
    },
    {
      "id": "c_264_3",
      "mentionId": "m_264_3",
      "centroid": [
        77.21538500000001,
        28.647960144789298
      ],
      "uncertaintyRadiusM": 253.6185139154708,
      "status": "candidate",
      "matchedBaselineFeature": {
        "id": "n2714555470",
        "name": "Kunwari Begum ka Burj",
        "distanceM": 170.35092909215805
      },
      "confidence": {
        "total": 0.5509875045715775,
        "parts": {
          "clueSpecificity": 0.6,
          "anchorPrecision": 0.45454545454545453,
          "sourceReliability": 0.9,
          "modernEvidence": 0.6641591213862748,
          "crossSourceAgreement": 0
        }
      },
      "evidence": {
        "anchorId": "qadam-sharif",
        "anchorName": "Qadam Sharif",
        "anchorSource": "osm:n2714497374",
        "anchorCentroid": [
          77.215385,
          28.646151
        ],
        "bearingDeg": 0,
        "distanceM": 201.168,
        "radiusParts": {
          "anchorPrecisionM": 120,
          "bearingSpreadM": 83.32651391547078,
          "distanceVaguenessM": 50.292,
          "floorTopUpM": 0
        },
        "baselineVerdict": "matched_existing",
        "baselineChecked": [
          {
            "id": "n2714555470",
            "name": "Kunwari Begum ka Burj",
            "distanceM": 170.35092909215805,
            "insideRadius": true
          },
          {
            "id": "n2714497374",
            "name": "Qadam Sharief s Tomb",
            "distanceM": 201.2124801620092,
            "insideRadius": false
          },
          {
            "id": "n2981346624",
            "name": "Graveyard",
            "distanceM": 271.40404792860704,
            "insideRadius": false
          },
          {
            "id": "n5389381021",
            "name": "Snooker tashi",
            "distanceM": 317.6759613712073,
            "insideRadius": false
          },
          {
            "id": "n6512337586",
            "name": "unnamed attraction (n6512337586)",
            "distanceM": 623.9071099168838,
            "insideRadius": false
          }
        ]
      }
    }
  ]
};

export default page;
