import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "openai/gpt-oss-120b",
  "pageNo": 65,
  "mentions": [
    {
      "id": "m_65_1",
      "name": "Unknown",
      "type": "tomb",
      "period": "Mughal",
      "passage": "Some 25 yards to the S. W. of No. 69.",
      "passageOffset": [
        246,
        283
      ],
      "spatialClue": {
        "anchorName": "No. 69",
        "bearing": "SW",
        "distanceValue": 25,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_65_2",
      "name": "Unknown",
      "type": "mosque",
      "period": "Afghan",
      "passage": "Some 180 yards to the north of No. 70 and 170 yards to the north of No. 72.",
      "passageOffset": [
        778,
        853
      ],
      "spatialClue": {
        "anchorName": "No. 70",
        "bearing": "N",
        "distanceValue": 180,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_65_3",
      "name": "Barah Khamba",
      "type": "gateway",
      "period": "Afghan",
      "passage": "Some 150 yards to the N. W. of the Railway Station Nizamuddin.",
      "passageOffset": [
        1261,
        1323
      ],
      "spatialClue": {
        "anchorName": "Railway Station Nizamuddin",
        "bearing": "NW",
        "distanceValue": 150,
        "distanceUnit": "yards"
      }
    }
  ],
  "candidates": [
    {
      "id": "c_65_3",
      "mentionId": "m_65_3",
      "centroid": [
        77.25216668223041,
        28.58726721812001
      ],
      "uncertaintyRadiusM": 327.3875322150937,
      "status": "candidate",
      "matchedBaselineFeature": {
        "id": "n10270699257",
        "name": "unnamed wayside_shrine (n10270699257)",
        "distanceM": 171.66348585719473
      },
      "confidence": {
        "total": 0.6163885320663707,
        "parts": {
          "clueSpecificity": 0.95,
          "anchorPrecision": 0.2857142857142857,
          "sourceReliability": 0.9,
          "modernEvidence": 0.7378283090139002,
          "crossSourceAgreement": 0
        }
      },
      "evidence": {
        "anchorId": "nizamuddin-railway-station",
        "anchorName": "Railway Station Nizamuddin",
        "anchorSource": "osm:w584241791",
        "anchorCentroid": [
          77.25316,
          28.586395
        ],
        "bearingDeg": 315,
        "distanceM": 137.16,
        "radiusParts": {
          "anchorPrecisionM": 250,
          "bearingSpreadM": 56.813532215093716,
          "distanceVaguenessM": 20.573999999999998,
          "floorTopUpM": 0
        },
        "baselineVerdict": "matched_existing",
        "baselineChecked": [
          {
            "id": "n10270699257",
            "name": "unnamed wayside_shrine (n10270699257)",
            "distanceM": 171.66348585719473,
            "insideRadius": true
          },
          {
            "id": "n1754574641",
            "name": "Tomb of Abdul Rahim Khan-i-Khanan",
            "distanceM": 414.1814560317583,
            "insideRadius": false
          },
          {
            "id": "w163778461",
            "name": "unnamed yes (w163778461)",
            "distanceM": 416.0557675702493,
            "insideRadius": false
          },
          {
            "id": "w163778457",
            "name": "unnamed yes (w163778457)",
            "distanceM": 416.75170073554614,
            "insideRadius": false
          },
          {
            "id": "w403809791",
            "name": "Royal Gateway",
            "distanceM": 498.7191784989337,
            "insideRadius": false
          }
        ]
      }
    }
  ]
};

export default page;
