import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "openai/gpt-oss-120b",
  "pageNo": 77,
  "mentions": [
    {
      "id": "m_77_1",
      "name": "Unknown",
      "type": "mosque",
      "period": "Late Mughal",
      "passage": "At the first mile-stone on Delhi-Muttra Road.",
      "passageOffset": [
        68,
        113
      ],
      "spatialClue": {
        "anchorName": "Delhi-Muttra Road",
        "bearing": "adjacent",
        "distanceValue": null,
        "distanceUnit": null
      }
    },
    {
      "id": "m_77_2",
      "name": "Unknown",
      "type": "fort_wall",
      "period": "Sher Shah(?)",
      "passage": "Some 100 yards to the west of No. 97.",
      "passageOffset": [
        356,
        393
      ],
      "spatialClue": {
        "anchorName": "No. 97",
        "bearing": "W",
        "distanceValue": 100,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_77_3",
      "name": "Unknown",
      "type": "mosque",
      "period": "Afghan",
      "passage": "Within the compound of the Reformatory school, some 100 yards to the S.-E. of the District Jail (No. 100).",
      "passageOffset": [
        683,
        789
      ],
      "spatialClue": {
        "anchorName": "District Jail",
        "bearing": "SE",
        "distanceValue": 100,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_77_4",
      "name": "Sarai of Nawab Shaikh Farid Khan, known as Murtaza Khan",
      "type": "caravanserai",
      "period": null,
      "passage": "About half a mile to the south of the Delhi gate of Shahjahanabad, occupying the centre of the enclosure of the District jail.",
      "passageOffset": [
        1174,
        1300
      ],
      "spatialClue": {
        "anchorName": "Delhi gate of Shahjahanabad",
        "bearing": "S",
        "distanceValue": 0.5,
        "distanceUnit": "miles"
      }
    }
  ],
  "candidates": [
    {
      "id": "c_77_1",
      "mentionId": "m_77_1",
      "centroid": [
        77.245877,
        28.590017
      ],
      "uncertaintyRadiusM": 2650,
      "status": "candidate",
      "matchedBaselineFeature": null,
      "confidence": {
        "total": 0.25303846153846155,
        "parts": {
          "clueSpecificity": 0.18,
          "anchorPrecision": 0.038461538461538464,
          "sourceReliability": 0.9,
          "modernEvidence": 0.35,
          "crossSourceAgreement": 0
        }
      },
      "evidence": {
        "anchorId": "delhi-muttra-road",
        "anchorName": "Delhi-Muttra Road",
        "anchorSource": "osm:w39013511",
        "anchorCentroid": [
          77.245877,
          28.590017
        ],
        "bearingDeg": null,
        "distanceM": null,
        "radiusParts": {
          "anchorPrecisionM": 2500,
          "bearingSpreadM": 0,
          "distanceVaguenessM": 150,
          "floorTopUpM": 0
        },
        "baselineVerdict": "inconclusive",
        "baselineChecked": [
          {
            "id": "w403809796",
            "name": "Mosque",
            "distanceM": 240.3110210678837,
            "insideRadius": true
          },
          {
            "id": "n1754574702",
            "name": "Isa Khan's Tomb",
            "distanceM": 247.87543731514705,
            "insideRadius": true
          },
          {
            "id": "w220385655",
            "name": "Arab Sarai",
            "distanceM": 275.6516524326265,
            "insideRadius": true
          },
          {
            "id": "w163778457",
            "name": "unnamed yes (w163778457)",
            "distanceM": 299.16425699765284,
            "insideRadius": true
          },
          {
            "id": "w163778461",
            "name": "unnamed yes (w163778461)",
            "distanceM": 299.6583176833827,
            "insideRadius": true
          }
        ]
      }
    },
    {
      "id": "c_77_4",
      "mentionId": "m_77_4",
      "centroid": [
        77.240564,
        28.63394442084281
      ],
      "uncertaintyRadiusM": 574.4740556618831,
      "status": "candidate",
      "matchedBaselineFeature": null,
      "confidence": {
        "total": 0.5517857142857143,
        "parts": {
          "clueSpecificity": 0.5,
          "anchorPrecision": 0.7142857142857143,
          "sourceReliability": 0.9,
          "modernEvidence": 0.35,
          "crossSourceAgreement": 0
        }
      },
      "evidence": {
        "anchorId": "delhi-gate-shahjahanabad",
        "anchorName": "Delhi gate of Shahjahanabad",
        "anchorSource": "osm:w973086054",
        "anchorCentroid": [
          77.240564,
          28.641181
        ],
        "bearingDeg": 180,
        "distanceM": 804.672,
        "radiusParts": {
          "anchorPrecisionM": 40,
          "bearingSpreadM": 333.30605566188314,
          "distanceVaguenessM": 201.168,
          "floorTopUpM": 0
        },
        "baselineVerdict": "inconclusive",
        "baselineChecked": [
          {
            "id": "w464253914",
            "name": "Khooni Darwaza",
            "distanceM": 232.1493770814548,
            "insideRadius": true
          },
          {
            "id": "w1256902982",
            "name": "unnamed ruins (w1256902982)",
            "distanceM": 284.856303255171,
            "insideRadius": true
          },
          {
            "id": "w97230893",
            "name": "Kotla Firoz Shah Ruins",
            "distanceM": 396.1620839137041,
            "insideRadius": true
          },
          {
            "id": "w97230898",
            "name": "Kotla Firoz Shah Palace",
            "distanceM": 418.29503410117496,
            "insideRadius": true
          },
          {
            "id": "w97230899",
            "name": "Baoli",
            "distanceM": 461.6915195523175,
            "insideRadius": true
          }
        ]
      }
    }
  ]
};

export default page;
