import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "gemini-3.5-flash",
  "pageNo": 149,
  "mentions": [
    {
      "id": "m_149_1",
      "name": "Tomb of Sayyid Yasin",
      "type": "tomb",
      "period": "Afghan",
      "passage": "Arab Sarai, at its western gateway.",
      "passageOffset": [
        1706,
        1741
      ],
      "spatialClue": {
        "anchorName": "Arab Sarai",
        "bearing": "adjacent",
        "distanceValue": null,
        "distanceUnit": null
      }
    },
    {
      "id": "m_149_2",
      "name": "Tomb of Ahmad Shah",
      "type": "tomb",
      "period": "Afghan",
      "passage": "Arab Sarai, at its western gateway,",
      "passageOffset": [
        2057,
        2092
      ],
      "spatialClue": {
        "anchorName": "Arab Sarai",
        "bearing": "adjacent",
        "distanceValue": null,
        "distanceUnit": null
      }
    }
  ],
  "candidates": [
    {
      "id": "c_149_1",
      "mentionId": "m_149_1",
      "centroid": [
        77.248252,
        28.591357
      ],
      "uncertaintyRadiusM": 240,
      "status": "candidate",
      "matchedBaselineFeature": {
        "id": "w1123372345",
        "name": "unnamed city_gate (w1123372345)",
        "distanceM": 62.845096632111925
      },
      "confidence": {
        "total": 0.4772556441445703,
        "parts": {
          "clueSpecificity": 0.18,
          "anchorPrecision": 0.5263157894736842,
          "sourceReliability": 0.9,
          "modernEvidence": 0.8690727153497668,
          "crossSourceAgreement": 0
        }
      },
      "evidence": {
        "anchorId": "arab-sarai",
        "anchorName": "Arab Sarai",
        "anchorSource": "osm:w220385655",
        "anchorCentroid": [
          77.248252,
          28.591357
        ],
        "bearingDeg": null,
        "distanceM": null,
        "radiusParts": {
          "anchorPrecisionM": 90,
          "bearingSpreadM": 0,
          "distanceVaguenessM": 150,
          "floorTopUpM": 0
        },
        "baselineVerdict": "matched_existing",
        "baselineChecked": [
          {
            "id": "w220385655",
            "name": "Arab Sarai",
            "distanceM": 0.04494220478426137,
            "insideRadius": false
          },
          {
            "id": "w1123372345",
            "name": "unnamed city_gate (w1123372345)",
            "distanceM": 62.845096632111925,
            "insideRadius": true
          },
          {
            "id": "w1174922273",
            "name": "Afsarwala's Tomb",
            "distanceM": 141.69405712555917,
            "insideRadius": true
          },
          {
            "id": "n2981346454",
            "name": "Afsarwala's Mosque",
            "distanceM": 162.31329626572074,
            "insideRadius": true
          },
          {
            "id": "w378119036",
            "name": "unnamed yes (w378119036)",
            "distanceM": 170.94044809816103,
            "insideRadius": true
          }
        ]
      }
    },
    {
      "id": "c_149_2",
      "mentionId": "m_149_2",
      "centroid": [
        77.248252,
        28.591357
      ],
      "uncertaintyRadiusM": 240,
      "status": "candidate",
      "matchedBaselineFeature": {
        "id": "w1123372345",
        "name": "unnamed city_gate (w1123372345)",
        "distanceM": 62.845096632111925
      },
      "confidence": {
        "total": 0.4772556441445703,
        "parts": {
          "clueSpecificity": 0.18,
          "anchorPrecision": 0.5263157894736842,
          "sourceReliability": 0.9,
          "modernEvidence": 0.8690727153497668,
          "crossSourceAgreement": 0
        }
      },
      "evidence": {
        "anchorId": "arab-sarai",
        "anchorName": "Arab Sarai",
        "anchorSource": "osm:w220385655",
        "anchorCentroid": [
          77.248252,
          28.591357
        ],
        "bearingDeg": null,
        "distanceM": null,
        "radiusParts": {
          "anchorPrecisionM": 90,
          "bearingSpreadM": 0,
          "distanceVaguenessM": 150,
          "floorTopUpM": 0
        },
        "baselineVerdict": "matched_existing",
        "baselineChecked": [
          {
            "id": "w220385655",
            "name": "Arab Sarai",
            "distanceM": 0.04494220478426137,
            "insideRadius": false
          },
          {
            "id": "w1123372345",
            "name": "unnamed city_gate (w1123372345)",
            "distanceM": 62.845096632111925,
            "insideRadius": true
          },
          {
            "id": "w1174922273",
            "name": "Afsarwala's Tomb",
            "distanceM": 141.69405712555917,
            "insideRadius": true
          },
          {
            "id": "n2981346454",
            "name": "Afsarwala's Mosque",
            "distanceM": 162.31329626572074,
            "insideRadius": true
          },
          {
            "id": "w378119036",
            "name": "unnamed yes (w378119036)",
            "distanceM": 170.94044809816103,
            "insideRadius": true
          }
        ]
      }
    }
  ]
};

export default page;
