import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "openai/gpt-oss-120b",
  "pageNo": 133,
  "mentions": [
    {
      "id": "m_133_1",
      "name": "Unknown",
      "type": "tomb",
      "period": "Mughal period",
      "passage": "Some 140 yards to the east of Mirza Muzaffar’s tomb (No. 151).",
      "passageOffset": [
        56,
        118
      ],
      "spatialClue": {
        "anchorName": "Mirza Muzaffar’s tomb",
        "bearing": "E",
        "distanceValue": 140,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_133_2",
      "name": "Unknown",
      "type": "tomb",
      "period": "974 A.H. (1566-7 A.D.)",
      "passage": "Some 40 yards to the S. W. of No. 153*.",
      "passageOffset": [
        725,
        764
      ],
      "spatialClue": {
        "anchorName": "No. 153",
        "bearing": "SW",
        "distanceValue": 40,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_133_3",
      "name": "Unknown",
      "type": "tomb",
      "period": "Mughal",
      "passage": "Some 200 yards to the north of No. 151.",
      "passageOffset": [
        1193,
        1232
      ],
      "spatialClue": {
        "anchorName": "No. 151",
        "bearing": "N",
        "distanceValue": 200,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_133_4",
      "name": "Unknown",
      "type": "tomb",
      "period": null,
      "passage": "Some 57 yards to the north of No. 155.",
      "passageOffset": [
        1533,
        1571
      ],
      "spatialClue": {
        "anchorName": "No. 155",
        "bearing": "N",
        "distanceValue": 57,
        "distanceUnit": "yards"
      }
    }
  ],
  "candidates": [
    {
      "id": "c_133_1",
      "mentionId": "m_133_1",
      "centroid": [
        77.25026121824034,
        28.595739993694814
      ],
      "uncertaintyRadiusM": 102.22836340075413,
      "status": "candidate",
      "matchedBaselineFeature": null,
      "confidence": {
        "total": 0.7032692307692308,
        "parts": {
          "clueSpecificity": 0.95,
          "anchorPrecision": 0.7692307692307693,
          "sourceReliability": 0.9,
          "modernEvidence": 0.35,
          "crossSourceAgreement": 0
        }
      },
      "evidence": {
        "anchorId": "mirza-muzaffar-tomb",
        "anchorName": "Mirza Muzaffar's tomb",
        "anchorSource": "osm:w348302815",
        "anchorCentroid": [
          77.24895,
          28.59574
        ],
        "bearingDeg": 90,
        "distanceM": 128.016,
        "radiusParts": {
          "anchorPrecisionM": 30,
          "bearingSpreadM": 53.02596340075413,
          "distanceVaguenessM": 19.202399999999997,
          "floorTopUpM": 0
        },
        "baselineVerdict": "representation_gap",
        "baselineChecked": [
          {
            "id": "w403809790",
            "name": "North Pavilion",
            "distanceM": 112.1716689281428,
            "insideRadius": false
          },
          {
            "id": "w348302815",
            "name": "Mirza Muzaffar Hussain’s Tomb",
            "distanceM": 127.65565948533254,
            "insideRadius": false
          },
          {
            "id": "w432131635",
            "name": "unnamed tomb (w432131635)",
            "distanceM": 181.12523305241524,
            "insideRadius": false
          },
          {
            "id": "w432131641",
            "name": "unnamed tomb (w432131641)",
            "distanceM": 181.9895001183579,
            "insideRadius": false
          },
          {
            "id": "w432131639",
            "name": "unnamed tomb (w432131639)",
            "distanceM": 182.84516891253304,
            "insideRadius": false
          }
        ]
      }
    }
  ]
};

export default page;
