import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "gemini-3.5-flash",
  "pageNo": 122,
  "mentions": [
    {
      "id": "m_122_1",
      "name": "Unknown",
      "type": "other",
      "period": "Late Pathan or early Mughal",
      "passage": "To the east of the Delhi-Muttra Road, between 1st and 2nd furlong past the second mile stone.",
      "passageOffset": [
        524,
        617
      ],
      "spatialClue": {
        "anchorName": "Delhi-Muttra Road",
        "bearing": "E",
        "distanceValue": null,
        "distanceUnit": null
      }
    },
    {
      "id": "m_122_2",
      "name": "Unknown",
      "type": "tomb",
      "period": "Mughal",
      "passage": "Some 80 yards from the S. E. corner of the Purana Qila, towards south.",
      "passageOffset": [
        904,
        974
      ],
      "spatialClue": {
        "anchorName": "Purana Qila",
        "bearing": "S",
        "distanceValue": 80,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_122_3",
      "name": "Unknown",
      "type": "temple",
      "period": null,
      "passage": "Some 250 yards from the south gate of the Purana Qila, in a south-easterly direction.",
      "passageOffset": null,
      "spatialClue": {
        "anchorName": "Purana Qila",
        "bearing": "SE",
        "distanceValue": 250,
        "distanceUnit": "yards"
      }
    }
  ],
  "candidates": [
    {
      "id": "c_122_1",
      "mentionId": "m_122_1",
      "centroid": [
        77.245877,
        28.590017
      ],
      "uncertaintyRadiusM": 2650,
      "status": "candidate",
      "matchedBaselineFeature": null,
      "confidence": {
        "total": 0.2890384615384615,
        "parts": {
          "clueSpecificity": 0.3,
          "anchorPrecision": 0.038461538461538464,
          "sourceReliability": 0.9,
          "modernEvidence": 0.35,
          "crossSourceAgreement": 0
        }
      },
      "evidence": {
        "anchorId": "delhi-muttra-road",
        "anchorName": "Delhi-Muttra Road",
        "anchorSource": "osm:w39013511",
        "anchorCentroid": [
          77.245877,
          28.590017
        ],
        "bearingDeg": 90,
        "distanceM": null,
        "radiusParts": {
          "anchorPrecisionM": 2500,
          "bearingSpreadM": 0,
          "distanceVaguenessM": 150,
          "floorTopUpM": 0
        },
        "baselineVerdict": "inconclusive",
        "baselineChecked": [
          {
            "id": "w403809796",
            "name": "Mosque",
            "distanceM": 240.3110210678837,
            "insideRadius": true
          },
          {
            "id": "n1754574702",
            "name": "Isa Khan's Tomb",
            "distanceM": 247.87543731514705,
            "insideRadius": true
          },
          {
            "id": "w220385655",
            "name": "Arab Sarai",
            "distanceM": 275.6516524326265,
            "insideRadius": true
          },
          {
            "id": "w163778457",
            "name": "unnamed yes (w163778457)",
            "distanceM": 299.16425699765284,
            "insideRadius": true
          },
          {
            "id": "w163778461",
            "name": "unnamed yes (w163778461)",
            "distanceM": 299.6583176833827,
            "insideRadius": true
          }
        ]
      }
    },
    {
      "id": "c_122_2",
      "mentionId": "m_122_2",
      "centroid": [
        77.244111,
        28.608538129167535
      ],
      "uncertaintyRadiusM": 261.27335051471664,
      "status": "candidate",
      "matchedBaselineFeature": {
        "id": "w545405140",
        "name": "Purana Qila Baoli",
        "distanceM": 78.55877932651292
      },
      "confidence": {
        "total": 0.6411992559693469,
        "parts": {
          "clueSpecificity": 0.95,
          "anchorPrecision": 0.3125,
          "sourceReliability": 0.9,
          "modernEvidence": 0.849661706462313,
          "crossSourceAgreement": 0
        }
      },
      "evidence": {
        "anchorId": "purana-qila",
        "anchorName": "Purana Qila",
        "anchorSource": "osm:w973075081",
        "anchorCentroid": [
          77.244111,
          28.609196
        ],
        "bearingDeg": 180,
        "distanceM": 73.152,
        "radiusParts": {
          "anchorPrecisionM": 220,
          "bearingSpreadM": 30.300550514716647,
          "distanceVaguenessM": 10.9728,
          "floorTopUpM": 0
        },
        "baselineVerdict": "matched_existing",
        "baselineChecked": [
          {
            "id": "w545405140",
            "name": "Purana Qila Baoli",
            "distanceM": 78.55877932651292,
            "insideRadius": true
          },
          {
            "id": "w973075080",
            "name": "unnamed citywalls (w973075080)",
            "distanceM": 92.94705595629863,
            "insideRadius": true
          },
          {
            "id": "w973075081",
            "name": "पुराना किला",
            "distanceM": 92.94705595629863,
            "insideRadius": false
          },
          {
            "id": "w233262400",
            "name": "Sher Mandal",
            "distanceM": 93.57055164172417,
            "insideRadius": true
          },
          {
            "id": "w370944290",
            "name": "unnamed yes (w370944290)",
            "distanceM": 117.7845296626425,
            "insideRadius": true
          }
        ]
      }
    }
  ]
};

export default page;
