import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "openai/gpt-oss-120b",
  "pageNo": 75,
  "mentions": [
    {
      "id": "m_75_1",
      "name": "Unknown",
      "type": "tomb",
      "period": null,
      "passage": "",
      "passageOffset": [
        0,
        0
      ],
      "spatialClue": null
    },
    {
      "id": "m_75_2",
      "name": "Mosque (nameless)",
      "type": "mosque",
      "period": "Mughal",
      "passage": "On the road from Humayun’s tomb to Safdar Jang, towards south, and some 30 yards to the north of No. 90.",
      "passageOffset": [
        479,
        583
      ],
      "spatialClue": {
        "anchorName": "Humayun’s tomb",
        "bearing": "N",
        "distanceValue": 30,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_75_3",
      "name": "Unknown",
      "type": "gateway",
      "period": "Mughal",
      "passage": "On the road from Humayun’s tomb to Safdar Jang, towards south, ajid some 60 yards to the west of No. 91.",
      "passageOffset": [
        861,
        965
      ],
      "spatialClue": {
        "anchorName": "Humayun’s tomb",
        "bearing": "W",
        "distanceValue": 60,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_75_4",
      "name": "Gol Gumbad",
      "type": "tomb",
      "period": "Afghan",
      "passage": "On the road from Humayun’s tomb to Safdar Jang, at the railway cross-\ning.",
      "passageOffset": [
        1315,
        1389
      ],
      "spatialClue": {
        "anchorName": "Humayun’s tomb",
        "bearing": "adjacent",
        "distanceValue": null,
        "distanceUnit": null
      }
    }
  ],
  "candidates": [
    {
      "id": "c_75_2",
      "mentionId": "m_75_2",
      "centroid": [
        77.250646,
        28.593532701562175
      ],
      "uncertaintyRadiusM": 135.47750644301874,
      "status": "candidate",
      "matchedBaselineFeature": {
        "id": "w432131635",
        "name": "unnamed tomb (w432131635)",
        "distanceM": 134.58153729063287
      },
      "confidence": {
        "total": 0.6318596425877929,
        "parts": {
          "clueSpecificity": 0.95,
          "anchorPrecision": 0.45454545454545453,
          "sourceReliability": 0.9,
          "modernEvidence": 0.5033067081610434,
          "crossSourceAgreement": 0
        }
      },
      "evidence": {
        "anchorId": "humayuns-tomb",
        "anchorName": "Humayun's Tomb",
        "anchorSource": "osm:w220385654",
        "anchorCentroid": [
          77.250646,
          28.593286
        ],
        "bearingDeg": 0,
        "distanceM": 27.432,
        "radiusParts": {
          "anchorPrecisionM": 120,
          "bearingSpreadM": 11.362706443018743,
          "distanceVaguenessM": 4.1148,
          "floorTopUpM": 0
        },
        "baselineVerdict": "matched_existing",
        "baselineChecked": [
          {
            "id": "w220385654",
            "name": "Humayun's Tomb",
            "distanceM": 27.40980445486169,
            "insideRadius": false
          },
          {
            "id": "w432131635",
            "name": "unnamed tomb (w432131635)",
            "distanceM": 134.58153729063287,
            "insideRadius": true
          },
          {
            "id": "w432131641",
            "name": "unnamed tomb (w432131641)",
            "distanceM": 136.2594306283928,
            "insideRadius": false
          },
          {
            "id": "w432131639",
            "name": "unnamed tomb (w432131639)",
            "distanceM": 137.99803820985036,
            "insideRadius": false
          },
          {
            "id": "w403809790",
            "name": "North Pavilion",
            "distanceM": 140.78841141216557,
            "insideRadius": false
          }
        ]
      }
    },
    {
      "id": "c_75_3",
      "mentionId": "m_75_3",
      "centroid": [
        77.25008406244501,
        28.593285998842024
      ],
      "uncertaintyRadiusM": 150.95501288603748,
      "status": "candidate",
      "matchedBaselineFeature": {
        "id": "w432131635",
        "name": "unnamed tomb (w432131635)",
        "distanceM": 119.37844629347599
      },
      "confidence": {
        "total": 0.6470520355043128,
        "parts": {
          "clueSpecificity": 0.95,
          "anchorPrecision": 0.45454545454545453,
          "sourceReliability": 0.9,
          "modernEvidence": 0.6045893276045096,
          "crossSourceAgreement": 0
        }
      },
      "evidence": {
        "anchorId": "humayuns-tomb",
        "anchorName": "Humayun's Tomb",
        "anchorSource": "osm:w220385654",
        "anchorCentroid": [
          77.250646,
          28.593286
        ],
        "bearingDeg": 270,
        "distanceM": 54.864,
        "radiusParts": {
          "anchorPrecisionM": 120,
          "bearingSpreadM": 22.725412886037486,
          "distanceVaguenessM": 8.2296,
          "floorTopUpM": 0
        },
        "baselineVerdict": "matched_existing",
        "baselineChecked": [
          {
            "id": "w220385654",
            "name": "Humayun's Tomb",
            "distanceM": 54.81518769975593,
            "insideRadius": false
          },
          {
            "id": "w432131635",
            "name": "unnamed tomb (w432131635)",
            "distanceM": 119.37844629347599,
            "insideRadius": true
          },
          {
            "id": "w432131641",
            "name": "unnamed tomb (w432131641)",
            "distanceM": 120.31029631422027,
            "insideRadius": true
          },
          {
            "id": "w432131639",
            "name": "unnamed tomb (w432131639)",
            "distanceM": 121.32407687310547,
            "insideRadius": true
          },
          {
            "id": "w432131640",
            "name": "unnamed tomb (w432131640)",
            "distanceM": 123.67471770995967,
            "insideRadius": true
          }
        ]
      }
    },
    {
      "id": "c_75_4",
      "mentionId": "m_75_4",
      "centroid": [
        77.250646,
        28.593286
      ],
      "uncertaintyRadiusM": 270,
      "status": "candidate",
      "matchedBaselineFeature": {
        "id": "w432131635",
        "name": "unnamed tomb (w432131635)",
        "distanceM": 152.3088448168304
      },
      "confidence": {
        "total": 0.4330556239145168,
        "parts": {
          "clueSpecificity": 0.18,
          "anchorPrecision": 0.45454545454545453,
          "sourceReliability": 0.9,
          "modernEvidence": 0.7179465836725363,
          "crossSourceAgreement": 0
        }
      },
      "evidence": {
        "anchorId": "humayuns-tomb",
        "anchorName": "Humayun's Tomb",
        "anchorSource": "osm:w220385654",
        "anchorCentroid": [
          77.250646,
          28.593286
        ],
        "bearingDeg": null,
        "distanceM": null,
        "radiusParts": {
          "anchorPrecisionM": 120,
          "bearingSpreadM": 0,
          "distanceVaguenessM": 150,
          "floorTopUpM": 0
        },
        "baselineVerdict": "matched_existing",
        "baselineChecked": [
          {
            "id": "w220385654",
            "name": "Humayun's Tomb",
            "distanceM": 0.0536437784595541,
            "insideRadius": false
          },
          {
            "id": "w432131635",
            "name": "unnamed tomb (w432131635)",
            "distanceM": 152.3088448168304,
            "insideRadius": true
          },
          {
            "id": "w432131641",
            "name": "unnamed tomb (w432131641)",
            "distanceM": 153.78750717128045,
            "insideRadius": true
          },
          {
            "id": "w432131639",
            "name": "unnamed tomb (w432131639)",
            "distanceM": 155.3320142540291,
            "insideRadius": true
          },
          {
            "id": "w432131640",
            "name": "unnamed tomb (w432131640)",
            "distanceM": 159.0348558992317,
            "insideRadius": true
          }
        ]
      }
    }
  ]
};

export default page;
