import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "openai/gpt-oss-120b",
  "pageNo": 59,
  "mentions": [
    {
      "id": "m_59_1",
      "name": "Unknown",
      "type": "tomb",
      "period": "Afghan",
      "passage": "",
      "passageOffset": [
        0,
        0
      ],
      "spatialClue": null
    },
    {
      "id": "m_59_2",
      "name": "Unknown",
      "type": "mosque",
      "period": "Afghan",
      "passage": " Some 50 yards to the east of the village and some 180 yards to S. E. of^ • No. 55.",
      "passageOffset": [
        514,
        596
      ],
      "spatialClue": {
        "anchorName": "village",
        "bearing": "E",
        "distanceValue": 50,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_59_3",
      "name": "Ruins of palaces",
      "type": "palace",
      "period": "Afghan",
      "passage": " Some 550 yards to the north of No. 56 and some 100 yards to the west of Purana Qila No. 123.",
      "passageOffset": [
        1422,
        1514
      ],
      "spatialClue": {
        "anchorName": "Purana Qila",
        "bearing": "W",
        "distanceValue": 100,
        "distanceUnit": "yards"
      }
    }
  ],
  "candidates": [
    {
      "id": "c_59_3",
      "mentionId": "m_59_3",
      "centroid": [
        77.24317429559748,
        28.609195996781274
      ],
      "uncertaintyRadiusM": 271.5916881433958,
      "status": "candidate",
      "matchedBaselineFeature": {
        "id": "w370944284",
        "name": "Bada Darwaza",
        "distanceM": 92.41631495787779
      },
      "confidence": {
        "total": 0.6382292498282154,
        "parts": {
          "clueSpecificity": 0.95,
          "anchorPrecision": 0.3125,
          "sourceReliability": 0.9,
          "modernEvidence": 0.8298616655214361,
          "crossSourceAgreement": 0
        }
      },
      "evidence": {
        "anchorId": "purana-qila",
        "anchorName": "Purana Qila",
        "anchorSource": "osm:w973075081",
        "anchorCentroid": [
          77.244111,
          28.609196
        ],
        "bearingDeg": 270,
        "distanceM": 91.44,
        "radiusParts": {
          "anchorPrecisionM": 220,
          "bearingSpreadM": 37.875688143395806,
          "distanceVaguenessM": 13.716,
          "floorTopUpM": 0
        },
        "baselineVerdict": "matched_existing",
        "baselineChecked": [
          {
            "id": "w370944284",
            "name": "Bada Darwaza",
            "distanceM": 92.41631495787779,
            "insideRadius": true
          },
          {
            "id": "w973075080",
            "name": "unnamed citywalls (w973075080)",
            "distanceM": 101.8278996449699,
            "insideRadius": true
          },
          {
            "id": "w973075081",
            "name": "पुराना किला",
            "distanceM": 101.8278996449699,
            "insideRadius": false
          },
          {
            "id": "w545405140",
            "name": "Purana Qila Baoli",
            "distanceM": 109.96588252367785,
            "insideRadius": true
          },
          {
            "id": "w80439684",
            "name": "unnamed yes (w80439684)",
            "distanceM": 156.40433411041766,
            "insideRadius": true
          }
        ]
      }
    }
  ]
};

export default page;
