import type { AnalyseResult } from "@/lib/types";

// generated by scripts/build-discovery-cache.ts
const page: AnalyseResult = {
  "source": "cached",
  "modelId": "openai/gpt-oss-120b",
  "pageNo": 45,
  "mentions": [
    {
      "id": "m_45_1",
      "name": "Unknown",
      "type": "mosque",
      "period": "Afghan",
      "passage": "Some 400 yards to the N. W. of Hijre ka Gumbad No. 59.",
      "passageOffset": [
        59,
        113
      ],
      "spatialClue": {
        "anchorName": "Hijre ka Gumbad",
        "bearing": "NW",
        "distanceValue": 400,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_45_2",
      "name": "Unknown",
      "type": "mosque",
      "period": null,
      "passage": "About ^ mile to the south of Agar Sains baoli No. 38 and i mile to the east of No. 35.",
      "passageOffset": [
        341,
        427
      ],
      "spatialClue": {
        "anchorName": "Agar Sains baoli",
        "bearing": "S",
        "distanceValue": 0.5,
        "distanceUnit": "miles"
      }
    },
    {
      "id": "m_45_3",
      "name": "Unknown",
      "type": "mosque",
      "period": "Mughal",
      "passage": "Some 200 yards to the south-east of No. 35.",
      "passageOffset": [
        678,
        721
      ],
      "spatialClue": {
        "anchorName": "No. 35",
        "bearing": "SE",
        "distanceValue": 200,
        "distanceUnit": "yards"
      }
    },
    {
      "id": "m_45_4",
      "name": "Tomb of Mir Muhammad Ali known as Sayyid ki Dargah",
      "type": "tomb",
      "period": null,
      "passage": "About half a mile to the south of Jantar Mantar No. 24.",
      "passageOffset": [
        1071,
        1126
      ],
      "spatialClue": {
        "anchorName": "Jantar Mantar",
        "bearing": "S",
        "distanceValue": 0.5,
        "distanceUnit": "miles"
      }
    }
  ],
  "candidates": [
    {
      "id": "c_45_2",
      "mentionId": "m_45_2",
      "centroid": [
        77.225012,
        28.618856420842807
      ],
      "uncertaintyRadiusM": 574.4740556618831,
      "status": "candidate",
      "matchedBaselineFeature": null,
      "confidence": {
        "total": 0.5517857142857143,
        "parts": {
          "clueSpecificity": 0.5,
          "anchorPrecision": 0.7142857142857143,
          "sourceReliability": 0.9,
          "modernEvidence": 0.35,
          "crossSourceAgreement": 0
        }
      },
      "evidence": {
        "anchorId": "agrasen-ki-baoli",
        "anchorName": "Agrasen ki Baoli",
        "anchorSource": "osm:w500411689",
        "anchorCentroid": [
          77.225012,
          28.626093
        ],
        "bearingDeg": 180,
        "distanceM": 804.672,
        "radiusParts": {
          "anchorPrecisionM": 40,
          "bearingSpreadM": 333.30605566188314,
          "distanceVaguenessM": 201.168,
          "floorTopUpM": 0
        },
        "baselineVerdict": "inconclusive",
        "baselineChecked": [
          {
            "id": "n14079933348",
            "name": "unnamed cannon (n14079933348)",
            "distanceM": 127.26051643748424,
            "insideRadius": true
          },
          {
            "id": "n7975753230",
            "name": "unnamed locomotive (n7975753230)",
            "distanceM": 650.951728817744,
            "insideRadius": false
          },
          {
            "id": "n9443637634",
            "name": "Param Yodha Sthal",
            "distanceM": 741.4656989620663,
            "insideRadius": false
          },
          {
            "id": "w361709652",
            "name": "India Gate",
            "distanceM": 790.6680713117704,
            "insideRadius": false
          },
          {
            "id": "w500411689",
            "name": "Agrasen ki Baoli",
            "distanceM": 804.6386424236447,
            "insideRadius": false
          }
        ]
      }
    },
    {
      "id": "c_45_4",
      "mentionId": "m_45_4",
      "centroid": [
        77.216596,
        28.619862420842814
      ],
      "uncertaintyRadiusM": 624.4740556618831,
      "status": "candidate",
      "matchedBaselineFeature": null,
      "confidence": {
        "total": 0.4953947368421052,
        "parts": {
          "clueSpecificity": 0.5,
          "anchorPrecision": 0.5263157894736842,
          "sourceReliability": 0.9,
          "modernEvidence": 0.35,
          "crossSourceAgreement": 0
        }
      },
      "evidence": {
        "anchorId": "jantar-mantar",
        "anchorName": "Jantar Mantar",
        "anchorSource": "osm:w223456559",
        "anchorCentroid": [
          77.216596,
          28.627099
        ],
        "bearingDeg": 180,
        "distanceM": 804.672,
        "radiusParts": {
          "anchorPrecisionM": 90,
          "bearingSpreadM": 333.30605566188314,
          "distanceVaguenessM": 201.168,
          "floorTopUpM": 0
        },
        "baselineVerdict": "inconclusive",
        "baselineChecked": [
          {
            "id": "n2323525225",
            "name": "Misra Yantra",
            "distanceM": 546.293390709068,
            "insideRadius": true
          },
          {
            "id": "n13760527971",
            "name": "unnamed locomotive (n13760527971)",
            "distanceM": 580.1422031045572,
            "insideRadius": true
          },
          {
            "id": "w500413800",
            "name": "Ram Yantra",
            "distanceM": 715.538880140468,
            "insideRadius": false
          },
          {
            "id": "w500413797",
            "name": "Ram Yantra",
            "distanceM": 744.0949376928604,
            "insideRadius": false
          },
          {
            "id": "w1137558568",
            "name": "Jai Prakash Yantra",
            "distanceM": 768.1608580417046,
            "insideRadius": false
          }
        ]
      }
    }
  ]
};

export default page;
