// generated by scripts/pull-zones.ts from OpenStreetMap way 220385656, ODbL
export const source = "OpenStreetMap way 220385656, ODbL";
export const centroid: [number, number] = [77.251898,28.592267];
export const zone: GeoJSON.Polygon = {
  type: "Polygon",
  coordinates: [
    [
      [77.2520308, 28.592388],
      [77.2520337, 28.592149],
      [77.2517657, 28.5921465],
      [77.2517628, 28.5923855],
      [77.2520308, 28.592388],
    ],
  ],
};
