// generated by scripts/pull-zones.ts from OpenStreetMap way 220385654, ODbL
export const source = "OpenStreetMap way 220385654, ODbL";
export const centroid: [number, number] = [77.250647,28.593286];
export const zone: GeoJSON.Polygon = {
  type: "Polygon",
  coordinates: [
    [
      [77.2501337, 28.5937093],
      [77.2511373, 28.5937289],
      [77.2511572, 28.5928619],
      [77.2501591, 28.5928434],
      [77.2501337, 28.5937093],
    ],
  ],
};
