// generated by scripts/pull-zones.ts from OpenStreetMap way 1448399383, ODbL
export const source = "OpenStreetMap way 1448399383, ODbL";
export const centroid: [number, number] = [77.242232,28.591537];
export const zone: GeoJSON.Polygon = {
  type: "Polygon",
  coordinates: [
    [
      [77.2421262, 28.5916154],
      [77.2421366, 28.5914483],
      [77.2423387, 28.5914579],
      [77.2423284, 28.591625],
      [77.2421262, 28.5916154],
    ],
  ],
};
