// generated by scripts/pull-zones.ts from OpenStreetMap way 103505909, ODbL
export const source = "OpenStreetMap way 103505909, ODbL";
export const centroid: [number, number] = [77.241976,28.59138];
export const zone: GeoJSON.Polygon = {
  type: "Polygon",
  coordinates: [
    [
      [77.241924, 28.5914207],
      [77.2419258, 28.5913367],
      [77.2420286, 28.5913384],
      [77.2420268, 28.5914224],
      [77.241924, 28.5914207],
    ],
  ],
};
