// generated by scripts/pull-zones.ts from OpenStreetMap way 103505910, ODbL
export const source = "OpenStreetMap way 103505910, ODbL";
export const centroid: [number, number] = [77.243041,28.591197];
export const zone: GeoJSON.Polygon = {
  type: "Polygon",
  coordinates: [
    [
      [77.242926, 28.5912997],
      [77.24293, 28.5910967],
      [77.2431572, 28.5910932],
      [77.2431493, 28.5912997],
      [77.242926, 28.5912997],
    ],
  ],
};
