// generated by scripts/pull-zones.ts from OpenStreetMap way 818709477, ODbL
export const source = "OpenStreetMap way 818709477, ODbL";
export const centroid: [number, number] = [77.185119,28.524737];
export const zone: GeoJSON.Polygon = {
  type: "Polygon",
  coordinates: [
    [
      [77.1848425, 28.5249558],
      [77.1848514, 28.5248797],
      [77.1852858, 28.5249187],
      [77.1853245, 28.5245857],
      [77.1848986, 28.5245475],
      [77.1849068, 28.5244773],
      [77.1854473, 28.5245257],
      [77.1853916, 28.525005],
      [77.1848425, 28.5249558],
    ],
  ],
};
