import type { Narration } from '../../lib/types';

export const diwanIKhasNarrations: Narration[] = [
  {
    "pointId": "red-fort/diwan-i-khas",
    "persona": "history",
    "lang": "en",
    "kind": "approach",
    "audioUrl": "/audio/red-fort/diwan-i-khas/history.en.mp3",
    "durationSec": 113.512,
    "sentences": [
      "Diwan-i-Khas is identified in historic records as the Hall of Private Audience of the Red Fort.",
      "Its construction period is recorded from AD 1639 to 1648.",
      "Unlike the public court, the emperor gave audience here specifically to select courtiers and nobles.",
      "This restricted audience made Diwan-i-Khas an exclusive center for private imperial council.",
      "The people named in the historical record were select nobles and high courtiers.",
      "The presiding figure giving private audience was the Mughal emperor.",
      "The hall had two courtyards situated on its west side.",
      "Both of these western courtyards were enclosed by arcaded colonnades.",
      "The Nahr-i-Bihisht channel ran directly through the centre of Diwan-i-Khas.",
      "Diwan-i-Khas is listed as part of the protected Red Fort monument.",
      "Its recorded history connects the date of construction between 1639 and 1648 to its imperial function.",
      "The presence of select courtiers and nobles defined the private nature of assembly here.",
      "Enclosed by colonnades and courtyards, the hall offered a secluded space for governance.",
      "The central stream of the Nahr-i-Bihisht added water to this private court setting.",
      "These facts document the solemn historical role of Diwan-i-Khas within the palace complex.",
      "The Hall of Private Audience remains a preserved component of the Red Fort.",
      "Its identity as a private court is preserved in the official archival inventory.",
      "Together, these recorded details form the history of Diwan-i-Khas."
    ],
    "cues": [
      0.1,
      7.5,
      14.212,
      21.662,
      29.112,
      35.175,
      40.125,
      44.675,
      50.612,
      55.937,
      61.3,
      70.5,
      77.137,
      84.15,
      89.862,
      96.512,
      102.1,
      108.2
    ],
    "factSheetId": "fs_diwan_i_khas"
  },
  {
    "pointId": "red-fort/diwan-i-khas",
    "persona": "architecture",
    "lang": "en",
    "kind": "approach",
    "audioUrl": "/audio/red-fort/diwan-i-khas/architecture.en.mp3",
    "durationSec": 107.45,
    "sentences": [
      "Diwan-i-Khas is recorded as twenty-seven point four metres long and twenty point four metres wide.",
      "The exterior ornamentation of Diwan-i-Khas is recorded as detailed pietra dura work.",
      "The interior ornamentation is documented as paintings decorative across the walls.",
      "The ceiling of Diwan-i-Khas is designed flat across the span of the hall.",
      "This flat ceiling is structurally supported on series of cusped arches.",
      "On its west side, Diwan-i-Khas featured two courtyards.",
      "Both of these western courtyards were enclosed by arcaded colonnades.",
      "The Nahr-i-Bihisht channel runs directly through the centre of the hall structure.",
      "The combination of flat ceiling and cusped arches defines the structural framework.",
      "Wall paintings enrich the interior surfaces of the Hall of Private Audience.",
      "Pietra dura craftsmanship highlights the exterior ornamentation of the pavilion.",
      "The arcaded colonnades surrounding the two western courtyards provided architectural enclosure.",
      "The central water channel of the Nahr-i-Bihisht integrates fluid movement into the stone architecture.",
      "Measuring twenty-seven point four by twenty point four metres, the hall displays balanced proportion.",
      "These structural arches, colonnades, paintings, and water channels express Mughal architectural design.",
      "All of these features are recorded in the historic property inventory of the Red Fort.",
      "Together, they define the complete architectural composition of Diwan-i-Khas."
    ],
    "cues": [
      0.1,
      7.75,
      14.787,
      21.162,
      26.862,
      32.575,
      37.262,
      43.2,
      48.675,
      54.787,
      60.612,
      66.612,
      73.3,
      80.262,
      87.362,
      95.462,
      101.737
    ],
    "factSheetId": "fs_diwan_i_khas"
  },
  {
    "pointId": "red-fort/diwan-i-khas",
    "persona": "kids",
    "lang": "en",
    "kind": "approach",
    "audioUrl": "/audio/red-fort/diwan-i-khas/kids.en.mp3",
    "durationSec": 46.887,
    "sentences": [
      "Diwan-i-Khas is the Hall of Private Audience in the Red Fort.",
      "It was built in the period recorded as AD 1639 to 1648.",
      "The emperor met select courtiers and nobles here.",
      "The hall is twenty-seven point four metres long and twenty point four metres wide.",
      "The hall has a flat ceiling.",
      "The ceiling is supported on cusped arches.",
      "There were two courtyards on the west side.",
      "Those courtyards had arcaded colonnades around them.",
      "The Nahr-i-Bihisht runs through the centre of the hall.",
      "The outside ornamentation is recorded as pietra dura.",
      "The inside ornamentation is recorded as paintings on the walls."
    ],
    "cues": [
      0.1,
      4.787,
      11.012,
      14.812,
      20.337,
      22.962,
      26.437,
      29.612,
      33.837,
      37.512,
      42
    ],
    "factSheetId": "fs_diwan_i_khas"
  },
  {
    "pointId": "red-fort/diwan-i-khas",
    "persona": "history",
    "lang": "en",
    "kind": "inside",
    "audioUrl": "/audio/red-fort/diwan-i-khas/history-inside.en.mp3",
    "durationSec": 18.375,
    "sentences": [
      "Inside Diwan-i-Khas, notice the stream of the Nahr-i-Bihisht running through the centre of the hall.",
      "Wall paintings ornament the interior surfaces of the hall.",
      "This water channel flowed through the room where the emperor met select courtiers and nobles."
    ],
    "cues": [
      0.1,
      6.887,
      11.6
    ],
    "factSheetId": "fs_diwan_i_khas"
  }
];
