import type { Narration } from '../../lib/types';

export const lahoriGateNarrations: Narration[] = [
  {
    "pointId": "red-fort/lahori-gate",
    "persona": "history",
    "lang": "en",
    "kind": "approach",
    "audioUrl": "/audio/red-fort/lahori-gate/history.en.mp3",
    "durationSec": 114.087,
    "sentences": [
      "Lahori Gate served as the primary main entrance to the Red Fort.",
      "It is situated on the western wall of the fort complex.",
      "The gateway received its historic name because it faced and led toward the city of Lahore.",
      "Historic records describe Lahori Gate as a magnificent three-storeyed structure.",
      "During his reign, Emperor Aurangzeb later screened Lahori Gate by adding a defensive barbican.",
      "The royal palaces of the Red Fort are approached directly from Lahori Gate.",
      "Visitors and court attendees passed through a covered passage known as Chhatta-Chowk.",
      "Chhatta-Chowk is recorded as a vaulted, roofed passage leading into the fort interior.",
      "This covered passage from Lahori Gate is flanked on both sides by double-storeyed arcaded apartments.",
      "Positioned on the western wall, the gate marked the formal entrance point into the imperial stronghold.",
      "The direction toward Lahore gave the gate its enduring historical title.",
      "Aurangzeb's addition of the barbican altered the initial historical approach to the entrance.",
      "Passing through the gate led immediately into the grand arcade of Chhatta-Chowk.",
      "The double-storeyed arcaded apartments lining the passage formed a central commercial and courtly corridor.",
      "These facts record how entry into the Red Fort was controlled and experienced.",
      "Lahori Gate connected the outer city route from Lahore to the inner palaces of the fort.",
      "Today, it remains the principal entrance recorded in historical backgrounders of the Red Fort.",
      "Together, these documented facts form the historical record of Lahori Gate."
    ],
    "cues": [
      0.1,
      5.037,
      9.375,
      16.237,
      22.237,
      29.637,
      35.25,
      41.612,
      48.112,
      55.812,
      63.237,
      68.587,
      75.012,
      80.887,
      88.287,
      94.775,
      101.112,
      108.2
    ],
    "factSheetId": "fs_lahori_gate"
  },
  {
    "pointId": "red-fort/lahori-gate",
    "persona": "architecture",
    "lang": "en",
    "kind": "approach",
    "audioUrl": "/audio/red-fort/lahori-gate/architecture.en.mp3",
    "durationSec": 102.95,
    "sentences": [
      "Lahori Gate is architecturally described as a magnificent three-storeyed gateway structure.",
      "The gate is clad in red sandstone across its massive outer elevation.",
      "It is situated on the western wall of the Red Fort monument.",
      "The gateway is flanked by tall semi-octagonal towers on either side.",
      "These semi-octagonal towers are crowned by two open octagonal pavilions.",
      "While the main structure uses red sandstone, the roofs of these octagonal pavilions use white stone.",
      "The facade of the gateway is decorated with square panels.",
      "It is also decorated with rectangular decorative panels.",
      "Series of cusped arched panels further ornament the stone surface.",
      "Emperor Aurangzeb later added an outer barbican screening the main gateway.",
      "From the gate, the approach path leads into Chhatta-Chowk, a roofed passage.",
      "This covered passage is flanked by double-storeyed arcaded apartments.",
      "The architectural contrast between red sandstone walls and white stone pavilion roofs defines its skyline.",
      "Semi-octagonal towers provide symmetry and verticality to the three-storeyed entrance facade.",
      "Square, rectangular, and cusped arched panels articulate the stone surface of the gateway.",
      "The roofed arcade of Chhatta-Chowk extends the architecture into a covered double-storeyed walkway.",
      "Together, these recorded elements constitute the complete architectural design of Lahori Gate."
    ],
    "cues": [
      0.1,
      6.712,
      12.55,
      17.162,
      22.8,
      28.55,
      36.212,
      40.75,
      45.2,
      50.362,
      56.25,
      61.912,
      67.237,
      75.375,
      82.112,
      89.2,
      95.875
    ],
    "factSheetId": "fs_lahori_gate"
  },
  {
    "pointId": "red-fort/lahori-gate",
    "persona": "kids",
    "lang": "en",
    "kind": "approach",
    "audioUrl": "/audio/red-fort/lahori-gate/kids.en.mp3",
    "durationSec": 47.962,
    "sentences": [
      "Lahori Gate is the main entrance of the Red Fort.",
      "It stands on the western wall of the fort.",
      "It got its name because it led toward Lahore.",
      "The gate is three storeys high.",
      "Aurangzeb later added a barbican in front of it.",
      "From Lahori Gate, people approach the palaces through Chhatta-Chowk.",
      "Chhatta-Chowk is a roofed passage.",
      "The passage has double-storeyed arcaded apartments on its sides.",
      "The gate is clad in red sandstone.",
      "The roofs of the octagonal pavilions use white stone.",
      "Tall semi-octagonal towers stand on the sides of the gateway.",
      "The gateway panels have square, rectangular, and cusped arched shapes."
    ],
    "cues": [
      0.1,
      3.875,
      7.175,
      10.762,
      13.55,
      17.662,
      22.862,
      25.787,
      30.625,
      33.737,
      37.837,
      42.475
    ],
    "factSheetId": "fs_lahori_gate"
  },
  {
    "pointId": "red-fort/lahori-gate",
    "persona": "history",
    "lang": "en",
    "kind": "inside",
    "audioUrl": "/audio/red-fort/lahori-gate/history-inside.en.mp3",
    "durationSec": 18.75,
    "sentences": [
      "Standing inside Lahori Gate, the covered passage called Chhatta-Chowk opens ahead of you.",
      "This roofed passage is flanked on both sides by double-storeyed arcaded apartments.",
      "It leads from the gate directly toward the palaces of the Red Fort."
    ],
    "cues": [
      0.1,
      6.812,
      13.475
    ],
    "factSheetId": "fs_lahori_gate"
  }
];
