import { IMAGES } from "@/content/images";
import type { HeritageSite } from "@/lib/types";

export const shallowSites: HeritageSite[] = [
  {
    id: "agrasen-ki-baoli",
    name: "Agrasen ki Baoli",
    nameLocal: "अग्रसेन की बावली",
    depth: "shallow",
    period: "Attributed to the Tughlaq or Lodi period, rebuilt",
    centroid: [77.225012, 28.626093],
    bbox: [77.2225, 28.6239, 77.2275, 28.6283],
    pointIds: [],
    blurb:
      "A hundred and three steps down to water that is no longer there, sunk between office towers off Hailey Road. Nobody knows who first cut it.",
    representationScore: 0.62,
    coordSource: "osm:w500411689",
    image: IMAGES["sites/agrasen-ki-baoli"],
  },
  {
    id: "feroz-shah-kotla",
    name: "Feroz Shah Kotla",
    nameLocal: "फ़ीरोज़ शाह कोटला",
    depth: "shallow",
    period: "Tughlaq, from 1354",
    centroid: [77.244331, 28.635271],
    bbox: [77.2415, 28.6328, 77.2475, 28.6378],
    pointIds: [],
    blurb:
      "The fifth city of Delhi, and the pillar Ashoka raised sixteen centuries earlier that Feroz Shah had carried here and set on its roof.",
    representationScore: 0.44,
    coordSource: "osm:w97230893",
    image: IMAGES["sites/feroz-shah-kotla"],
  },
  {
    id: "rajon-ki-baoli",
    name: "Rajon ki Baoli",
    nameLocal: "राजों की बावली",
    depth: "shallow",
    period: "Lodi, 1506",
    centroid: [77.183377, 28.520306],
    bbox: [77.1808, 28.5181, 77.1858, 28.5225],
    pointIds: [],
    blurb:
      "A three-storey stepwell in Mehrauli that took its name from the masons who later camped in it. Daulat Khan built it in Sikandar Lodi's reign.",
    representationScore: 0.28,
    coordSource: "osm:w89583611",
    image: IMAGES["sites/rajon-ki-baoli"],
  },
  {
    id: "zafar-mahal",
    name: "Zafar Mahal",
    nameLocal: "ज़फ़र महल",
    depth: "shallow",
    period: "Mughal, 18th to 19th century",
    centroid: [77.17945, 28.51885],
    bbox: [77.177, 28.5167, 77.182, 28.521],
    pointIds: [],
    blurb:
      "The last building the Mughals put up in Delhi. Bahadur Shah Zafar meant to be buried in the empty plot beside it and died exiled in Rangoon instead.",
    representationScore: 0.24,
    coordSource: "approximate",
    image: IMAGES["sites/zafar-mahal"],
  },
  {
    id: "bhuli-bhatiyari-ka-mahal",
    name: "Bhuli Bhatiyari ka Mahal",
    nameLocal: "भूली भटियारी का महल",
    depth: "shallow",
    period: "Tughlaq, 14th century",
    centroid: [77.20385, 28.64175],
    bbox: [77.2013, 28.6396, 77.2063, 28.6439],
    pointIds: [],
    blurb:
      "A Tughlaq hunting lodge in the Central Ridge, reached on foot through scrub. Better known now for the stories told about it than for anything recorded of it.",
    representationScore: 0.15,
    coordSource: "approximate",
    image: IMAGES["sites/bhuli-bhatiyari-ka-mahal"],
  },
  {
    id: "satpula",
    name: "Satpula",
    nameLocal: "सतपुला",
    depth: "shallow",
    period: "Tughlaq, 14th century",
    centroid: [77.223601, 28.531689],
    bbox: [77.2211, 28.5295, 77.2261, 28.5339],
    pointIds: [],
    blurb:
      "A seven-arched dam in the wall of Jahanpanah that watered the fields south of the city. Its water was held to cure, and people carried it away by the potful.",
    representationScore: 0.22,
    coordSource: "osm:w204969641",
    image: IMAGES["sites/satpula"],
  },
  {
    id: "chausath-khamba",
    name: "Chausath Khamba",
    nameLocal: "चौंसठ खंभा",
    depth: "shallow",
    period: "Mughal, 1623 to 1624",
    centroid: [77.243042, 28.591196],
    bbox: [77.2405, 28.589, 77.2455, 28.5934],
    pointIds: [],
    blurb:
      "Sixty-four marble pillars holding a flat roof over the grave of Mirza Aziz Koka, Akbar's foster brother. All of it is one material and one colour.",
    representationScore: 0.36,
    coordSource: "osm:w103505910",
    image: IMAGES["sites/chausath-khamba"],
  },
  {
    id: "lal-gumbad",
    name: "Lal Gumbad",
    nameLocal: "लाल गुंबद",
    depth: "shallow",
    period: "Tughlaq, 1397",
    centroid: [77.213669, 28.540094],
    bbox: [77.2112, 28.5379, 77.2162, 28.5423],
    pointIds: [],
    blurb:
      "The tomb of the saint Kabiruddin Auliya, standing in red sandstone in the middle of a Malviya Nagar park. Thieves once cut a hole in it, and the hole is still there.",
    representationScore: 0.14,
    coordSource: "osm:w96679854",
    image: IMAGES["sites/lal-gumbad"],
  },
];
